package codacy.com.commitviewer.util;

public enum CommitOption {
    SHA, AUTHOR_DATE, AUTHOR_NAME, AUTHOR_EMAIL, COMMITTER_DATE, COMMITTER_NAME, COMMITTER_EMAIL, MESSAGE, TREE_SHA,
    PARENT_SHA, VALIDATION
}
