spring:
  data:
    mongodb:
      host: localhost
      database: commit-viewer-mongodb

---
spring:
  profiles:
    active: docker
  data:
    mongodb:
      host: mongodb
      database: commit-viewer-mongodb